'use server'

import { createClient, createAdminClient } from '@/lib/supabase/server'
import { revalidatePath } from 'next/cache'
import { APP_URL } from '@/lib/constants'
import { sendInvitationEmail } from '@/lib/email/resend'

const TENANT_ROLES = ['technician', 'dispatcher', 'company_admin'] as const
export type TenantRole = 'technician' | 'dispatcher' | 'company_admin'

const ROLE_LABELS: Record<string, string> = {
  technician:    'Technician',
  dispatcher:    'Dispatcher',
  company_admin: 'Company Admin',
}

async function requireTenantAdmin(tenantId: string) {
  const supabase = await createClient()
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) return { error: 'Unauthenticated' as const, user: null, supabase: null }

  const { data: membership } = await supabase
    .from('memberships')
    .select('role')
    .eq('user_id', user.id)
    .eq('tenant_id', tenantId)
    .eq('is_active', true)
    .single()

  if (membership?.role !== 'company_admin') return { error: 'Unauthorized' as const, user: null, supabase: null }
  return { error: null, user, supabase }
}

export interface InviteTeamMemberInput {
  tenantId: string
  email: string
  firstName: string
  lastName: string
  role: TenantRole
}

export async function inviteTeamMember(
  input: InviteTeamMemberInput,
): Promise<{ ok: true } | { error: string }> {
  const { error: authError, user, supabase } = await requireTenantAdmin(input.tenantId)
  if (authError || !user || !supabase) return { error: authError ?? 'Unauthorized' }

  if (!TENANT_ROLES.includes(input.role)) return { error: 'Invalid role' }

  const email = input.email.toLowerCase().trim()

  // Check if this email already belongs to an active member
  const { data: existingProfile } = await supabase
    .from('profiles').select('id').eq('email', email).single()

  if (existingProfile) {
    const { data: activeMembership } = await supabase
      .from('memberships')
      .select('id')
      .eq('user_id', existingProfile.id)
      .eq('tenant_id', input.tenantId)
      .eq('is_active', true)
      .single()
    if (activeMembership) return { error: 'This person is already a member of your team.' }
  }

  // Check for an unexpired pending invitation
  const { data: existingInvite } = await supabase
    .from('invitations')
    .select('id, expires_at')
    .eq('email', email)
    .eq('tenant_id', input.tenantId)
    .is('accepted_at', null)
    .is('revoked_at', null)
    .single()

  if (existingInvite && new Date(existingInvite.expires_at) > new Date()) {
    return { error: 'This person already has a pending invitation.' }
  }

  // Create invitation (token auto-generated by the DB default)
  const admin = await createAdminClient()
  const { data: invitation, error: insertError } = await admin
    .from('invitations')
    .insert({
      tenant_id: input.tenantId,
      email,
      role: input.role,
      invited_by: user.id,
    })
    .select('token')
    .single()

  if (insertError || !invitation) return { error: 'Failed to create invitation' }

  // Fetch inviter name + tenant name for the email
  const [{ data: profile }, { data: tenant }] = await Promise.all([
    supabase.from('profiles').select('first_name, last_name').eq('id', user.id).single(),
    supabase.from('tenants').select('name').eq('id', input.tenantId).single(),
  ])

  const inviterName = profile
    ? [profile.first_name, profile.last_name].filter(Boolean).join(' ') || 'Your team admin'
    : 'Your team admin'

  // Send the branded Fieldpiece Digital email via Resend
  await sendInvitationEmail({
    to: email,
    inviterName,
    companyName: tenant?.name ?? 'your company',
    role: ROLE_LABELS[input.role] ?? input.role,
    inviteUrl: `${APP_URL}/accept-invite?token=${invitation.token}`,
  })

  revalidatePath('/team')
  return { ok: true }
}

export async function resendInvite(
  invitationId: string,
  tenantId: string,
): Promise<{ ok: true } | { error: string }> {
  const { error: authError, user, supabase } = await requireTenantAdmin(tenantId)
  if (authError || !user || !supabase) return { error: authError ?? 'Unauthorized' }

  const admin = await createAdminClient()

  const { data: invitation } = await admin
    .from('invitations')
    .select('email, role, token, expires_at')
    .eq('id', invitationId)
    .eq('tenant_id', tenantId)
    .is('accepted_at', null)
    .is('revoked_at', null)
    .single()

  if (!invitation) return { error: 'Invitation not found' }

  let token = invitation.token

  // If the invite has expired, revoke it and create a fresh one
  if (new Date(invitation.expires_at) < new Date()) {
    await admin.from('invitations')
      .update({ revoked_at: new Date().toISOString() })
      .eq('id', invitationId)

    const { data: fresh } = await admin.from('invitations')
      .insert({ tenant_id: tenantId, email: invitation.email, role: invitation.role, invited_by: user.id })
      .select('token')
      .single()

    if (!fresh) return { error: 'Failed to create new invitation' }
    token = fresh.token
  }

  const [{ data: profile }, { data: tenant }] = await Promise.all([
    supabase.from('profiles').select('first_name, last_name').eq('id', user.id).single(),
    supabase.from('tenants').select('name').eq('id', tenantId).single(),
  ])

  const inviterName = profile
    ? [profile.first_name, profile.last_name].filter(Boolean).join(' ') || 'Your team admin'
    : 'Your team admin'

  await sendInvitationEmail({
    to: invitation.email,
    inviterName,
    companyName: tenant?.name ?? 'your company',
    role: ROLE_LABELS[invitation.role] ?? invitation.role,
    inviteUrl: `${APP_URL}/accept-invite?token=${token}`,
  })

  revalidatePath('/team')
  return { ok: true }
}

export async function revokeInvite(
  invitationId: string,
  tenantId: string,
): Promise<{ ok: true } | { error: string }> {
  const { error: authError } = await requireTenantAdmin(tenantId)
  if (authError) return { error: authError }

  const supabase = await createClient()
  const { error } = await supabase
    .from('invitations')
    .update({ revoked_at: new Date().toISOString() })
    .eq('id', invitationId)
    .eq('tenant_id', tenantId)
    .is('accepted_at', null)

  if (error) return { error: error.message }
  revalidatePath('/team')
  return { ok: true }
}

export async function updateMemberRole(
  membershipId: string,
  tenantId: string,
  role: TenantRole,
): Promise<{ ok: true } | { error: string }> {
  const { error: authError } = await requireTenantAdmin(tenantId)
  if (authError) return { error: authError }
  if (!TENANT_ROLES.includes(role)) return { error: 'Invalid role' }

  const supabase = await createClient()
  const { error } = await supabase
    .from('memberships')
    .update({ role })
    .eq('id', membershipId)
    .eq('tenant_id', tenantId)

  if (error) return { error: error.message }
  revalidatePath('/team')
  return { ok: true }
}

export async function deactivateMember(
  membershipId: string,
  tenantId: string,
): Promise<{ ok: true } | { error: string }> {
  const { error: authError, user } = await requireTenantAdmin(tenantId)
  if (authError || !user) return { error: authError ?? 'Unauthorized' }

  const supabase = await createClient()
  const { error } = await supabase
    .from('memberships')
    .update({ is_active: false })
    .eq('id', membershipId)
    .eq('tenant_id', tenantId)
    .neq('user_id', user.id)

  if (error) return { error: error.message }
  revalidatePath('/team')
  return { ok: true }
}
